apiVersion: apps/v1
kind: Deployment
metadata:
  name: phase1-deployment
  namespace: test-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phase1
  template:
    metadata:
      labels:
        app: phase1
    spec:
      containers:
        - name: phase1
          image: datawindtunnel/phase1-service:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
          env:
            - name: KAFKA_BOOTSTRAP
              value: "kafka-service:9092"
            - name: BASE_PATH
              value: "/tmp"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "opentelemetrycollector:4317"
      volumes:
        - name: tmp-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: phase1-service
  namespace: test-pipeline
spec:
  selector:
    app: phase1
  ports:
    - protocol: TCP
      port: 3000  # The port you want to expose externally
      targetPort: 3000
  type: ClusterIP